package com.example.ffmpegmcp;

import no.lau.mcp.file.FileManager;
import no.lau.mcp.file.FileManagerUtils;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;

public class FileManagerFake implements FileManager {
    
    private final Map<String, Path> targetVideoReferences = new HashMap<>();

    public <V, K> FileManagerFake(Map<String, Path> testFiles) {
        targetVideoReferences.put("hello", Path.of("world"));
        this.targetVideoReferences.putAll(testFiles);
    }

    @Override
    public Map<String, Path> listVideoReferences() {
        return new HashMap<>(targetVideoReferences);
    }

    @Override
    public Path createNewFileWithAutoGeneratedNameInSecondFolder(String extension) throws IOException {
        Path tempfile = Files.createTempFile("ffmpeg", extension);
        tempfile.toFile().deleteOnExit();
        return tempfile;
    }

    @Override
    public String replaceVideoReferences(String command) {
        return FileManagerUtils.replaceVideoReferences(command, targetVideoReferences);
    }
    
    @Override
    public Map<String, Path> getTargetVideoReferences() {
        return new HashMap<>(targetVideoReferences);
    }
    
    @Override
    public void addTargetVideoReference(String id, Path path) {
        targetVideoReferences.put(id, path);
    }
}
