package com.example.ffmpegmcp;

import no.lau.mcp.file.FileManager;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;

public class FileManagerFake implements FileManager {

    public <V, K> FileManagerFake(Map<String, Path> testFiles) {
        targetVideoReferences.put("hello", Path.of("world"));
        this.targetVideoReferences.putAll(testFiles);
    }

    @Override
    public Map<String, Path> listVideoReferences() {
        return targetVideoReferences;
    }

    @Override
    public Path createNewFileWithAutoGeneratedNameInSecondFolder(String extension) throws IOException {
        Path tempfile = Files.createTempFile("ffmpeg", extension);
        tempfile.toFile().deleteOnExit();
        return tempfile;
    }

    @Override
    public String replaceVideoReferences(String command) {
        return FileManager.replaceVideoReferences(command, targetVideoReferences);
    }
}
