package com.example.ffmpegmcp;

import no.lau.mcp.file.FileManager;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;

public class FileManagerFake implements FileManager {
    private final Map<String, Path> fileRegistry = new HashMap<>();

    public <V, K> FileManagerFake(Map<String, Path> testFiles) {
        fileRegistry.put("hello", Path.of("world"));
        this.fileRegistry.putAll(testFiles);
    }

    @Override
    public Map<String, Path> listFilesWithGeneratedKeys() {
        return fileRegistry;
    }

    @Override
    public Set<String> listVideoReferences() {
        return listFilesWithGeneratedKeys().keySet();
    }

    @Override
    public Path createNewFileWithAutoGeneratedNameInSecondFolder(String extension) throws IOException {
        Path tempfile = Files.createTempFile("ffmpeg", extension);
        tempfile.toFile().deleteOnExit();
        return tempfile;
    }

    @Override
    public String replaceVideoReferences(String command) {
        return FileManager.replaceVideoReferences(command, fileRegistry);
    }
}
