name: Java CI with Maven

on:
  push:
    branches: [ "main", "changed-to-lau.no" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'oracle'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Test with Maven
      run: mvn -B test --file pom.xml
      
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-jar
        path: target/ffmpeg-*.jar

  publish:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'oracle'
        cache: maven
        server-id: github
    
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: app-jar
        path: target/
    
    - name: Configure Maven for GitHub Packages
      run: |
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>${GITHUB_ACTOR}</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Publish to GitHub Packages
      run: |
        mvn deploy:deploy-file \
          -DgroupId=no.lau.mcp \
          -DartifactId=ffmpeg \
          -Dversion=0.1.0-SNAPSHOT \
          -Dpackaging=jar \
          -Dfile=target/ffmpeg-0.1.0.jar \
          -DrepositoryId=github \
          -Durl=https://maven.pkg.github.com/StigLau/ffmpeg-mcp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}